notifications:
  webhooks:
    - https://discordapp.com/api/webhooks/517358448883793950/l4H7FDzqEMBuFJurmMGPFRgrwfOZaqGNTBeR4yhLxvqlTvVudvvXsil5krjwx2Kq4LOW

services:
  - docker

before_install:
  - docker pull garland/aws-cli-docker
  - docker run -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY -v $(pwd):/tmp garland/aws-cli-docker aws s3 cp s3://$AWS_S3_BUCKET/sourceforts.7z /tmp/sourceforts.7z
  - docker pull sourceforts/7zip
  - docker run -v $(pwd):/tmp sourceforts/7zip 7za e -r -aoa -o/tmp/sourceforts /tmp/sourceforts.7z
  - rm -f sourceforts.7z

script:
  - docker build -t sourceforts/server:$TRAVIS_BUILD_NUMBER -t sourceforts/server:latest .

before_deploy:
  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

deploy:
  provider: script
  script: bash .travisci/deploy.sh
  on:
    branch: master