services:
  - docker

script:
  - docker pull garland/aws-cli-docker
  - docker run -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY -v $(pwd):/tmp garland/aws-cli-docker aws s3 cp s3://$AWS_S3_BUCKET/sourceforts.7z /tmp/sourceforts.7z
  - docker pull sourceforts/7zip
  - docker run -w /tmp -v $(pwd):/tmp sourceforts/7zip 7za x sourceforts.7z
  - rm -f sourceforts.7z
  - ls -l sourceforts
  - sudo chmod -R 777 sourceforts # lol
  - docker build -t sourceforts/server:$TRAVIS_BUILD_NUMBER -t sourceforts/server:latest .

before_deploy:
  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

deploy:
  provider: script
  script: bash .travisci/deploy.sh
  on:
    branch: master

after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $DISCORD_WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $DISCORD_WEBHOOK_URL
