language: node_js
node_js:
  - "4.2"

services:
  - docker

script:
  - docker pull garland/aws-cli-docker
  - docker run -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY -v $(pwd):/tmp garland/aws-cli-docker aws s3 cp s3://$AWS_S3_BUCKET/sfclassic.7z /tmp/sfclassic.7z
  - docker pull pistonsh/7zip
  - docker run -w /tmp -v $(pwd):/tmp pistonsh/7zip 7za x sfclassic.7z
  - rm -f sfclassic.7z
  - sudo chmod -R 777 sfclassic # lol
  - docker build --build-arg version=$TRAVIS_BUILD_NUMBER -t pistonsh/sfclassic:$TRAVIS_BUILD_NUMBER -t pistonsh/sfclassic:latest .

before_deploy:
  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

deploy:
  provider: script
  script: bash .travisci/deploy.sh
  on:
    branch: master

after_success:
  - ./.travisci/send.sh success $DISCORD_WEBHOOK_URL
  # - docker run -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY garland/aws-cli-docker aws sns publish --region $AWS_REGION --topic-arn $AWS_TOPIC_ARN --message $TRAVIS_BUILD_NUMBER
after_failure:
  - ./.travisci/send.sh failure $DISCORD_WEBHOOK_URL
