version: 2

jobs:
  download:
    working_directory: /sourceforts-server
    docker:
      - image: garland/aws-cli-docker:latest
    steps:
      - run: aws s3 cp s3://$AWS_S3_BUCKET/sourceforts.7z sourceforts.7z
  unarchive:
    working_directory: /sourceforts-server
    docker:
      - image: sourceforts/7zip
    steps:
      - run: 7za e -r -aoa -osourceforts sourceforts.7z
  build:
    working_directory: /sourceforts-server
    machine: true
    steps:
      - setup_remote_docker
      - checkout
      - run: |
          docker build -t sourceforts/server:$CIRCLE_BUILD_NUM -t sourceforts/server:latest .
  deploy:
    machine: true
    steps:
      - setup_remote_docker
      - run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          docker push sourceforts/server:$CIRCLE_BUILD_NUM
          docker push sourceforts/server:latest

workflows:
  version: 2
  main:
    jobs:
      - download:
          context: sourceforts-server
      - unarchive:
          requires:
            - download
      - build:
          requires:
            - unarchive
      - deploy:
          context: sourceforts-server
          requires:
            - build