version: 2

persistence: &persistence
  persist_to_workspace:
    root: ./
    paths:
      - ./

jobs:
  checkout:
    working_directory: /tmp/workspace
    machine: true
    steps:
      - checkout
      - *persistence
  download:
    working_directory: /tmp/workspace
    docker:
      - image: garland/aws-cli-docker:latest
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: aws s3 cp s3://$AWS_S3_BUCKET/sourceforts.7z sourceforts.7z
      - *persistence
  unarchive:
    working_directory: /tmp/workspace
    docker:
      - image: sourceforts/7zip
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: 7za sourceforts sourceforts.7z
      - *persistence
  build:
    working_directory: /tmp/workspace
    machine: true
    steps:
      - docker build -t sourceforts/server:$CIRCLE_BUILD_NUM -t sourceforts/server:latest .
  deploy:
    working_directory: /tmp/workspace
    machine: true
    steps:
      - run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          docker push sourceforts/server:$CIRCLE_BUILD_NUM
          docker push sourceforts/server:latest

workflows:
  version: 2
  main:
    jobs:
      - checkout
      - download:
          context: sourceforts-server
          requires:
            - checkout
      - unarchive:
          requires:
            - download
      - build:
          requires:
            - unarchive
      - deploy:
          context: sourceforts-server
          requires:
            - build