version: 2

jobs:
  download:
    working_directory: /sourceforts-server
    docker:
      - image: garland/aws-cli-docker:latest
    steps:
      - attach_workspace:
          at: /sourceforts-server
      - checkout
      - run: aws s3 cp s3://$AWS_S3_BUCKET/sourceforts.7z sourceforts.7z
      - persist_to_workspace:
          root: ./
          paths:
            - cfg
            - Dockerfile
            - start.sh
            - sourceforts.7z
            - sourceforts_update.txt
  unarchive:
    working_directory: /sourceforts-server
    docker:
      - image: sourceforts/7zip
    steps:
      - attach_workspace:
          at: /sourceforts-server
      - run: |
          7za e -r -aoa -osourceforts sourceforts.7z
          rm -f sourceforts.7z
      - persist_to_workspace:
          root: ./
          paths:
            - sourceforts
  build:
    working_directory: /sourceforts-server
    docker:
      - image: docker
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: /sourceforts-server
      - run: |
          docker build -t sourceforts/server:$CIRCLE_BUILD_NUM -t sourceforts/server:latest .
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          docker push sourceforts/server:$CIRCLE_BUILD_NUM
          docker push sourceforts/server:latest
          
  build-dedicated-server:
    working_directory: /sourceforts-server
    docker:
      - image: docker
        environment:
          STEAM_USERNAME: $STEAM_USERNAME
          STEAM_PASSWORD: $STEAM_PASSWORD
    steps:
      - setup_remote_docker
      - checkout
      - run:
          command: |
            docker build --build-arg steam_username=$STEAM_USERNAME --build-arg steam_password=$STEAM_PASSWORD -t sourceforts/source-dedicated-server:$CIRCLE_BUILD_NUM -t sourceforts/source-dedicated-server:latest ./source-dedicated-server
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
            docker push sourceforts/source-dedicated-server:$CIRCLE_BUILD_NUM
            docker push sourceforts/source-dedicated-server:latest
  build-steamcmd:
    working_directory: /sourceforts-server
    docker:
      - image: docker
    steps:
      - setup_remote_docker
      - checkout
      - run: |
          docker build -t sourceforts/steamcmd:$CIRCLE_BUILD_NUM -t sourceforts/steamcmd:latest ./steamcmd
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          docker push sourceforts/steamcmd:$CIRCLE_BUILD_NUM
          docker push sourceforts/steamcmd:latest
        
workflows:
  version: 2
  server:
    jobs:
      - download:
          context: sourceforts-server
      - unarchive:
          requires:
            - download
      - build:
          context: sourceforts-server
          requires:
            - unarchive
  source-dedicated-server:
    jobs:
      - hold-build-dedicated-server:
          type: approval
      - build-dedicated-server:
          context: sourceforts-server
          requires:
            - hold-build-dedicated-server
  steamcmd:
    jobs:
      - hold-build-steamcmd:
          type: approval
      - build-steamcmd:
          context: sourceforts-server
          requires:
            - hold-build-steamcmd
