version: 2

jobs:
  download:
    working_directory: /sourceforts-server
    docker:
      - image: garland/aws-cli-docker
    steps:
      - attach_workspace:
          at: /sourceforts-server
      - checkout
      - run: aws s3 cp s3://$AWS_S3_BUCKET/sourceforts.7z sourceforts.7z
      - persist_to_workspace:
          root: ./
          paths:
            - cfg
            - init.d
            - sourceforts.7z
            - sourceforts_update.txt
            - Dockerfile
  unarchive:
    working_directory: /sourceforts-server
    docker:
      - image: sourceforts/7zip
    steps:
      - attach_workspace:
          at: /sourceforts-server
      - run: |
          7za e -r -aoa -osourceforts sourceforts.7z
          rm -f sourceforts.7z
      - persist_to_workspace:
          root: ./
          paths:
            - sourceforts
  build:
    working_directory: /sourceforts-server
    docker:
      - image: docker
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: /sourceforts-server
      - run: |
          docker build -t sourceforts/server:$CIRCLE_BUILD_NUM -t sourceforts/server:latest .
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          docker push sourceforts/server:$CIRCLE_BUILD_NUM
          docker push sourceforts/server:latest
  build-gdb:
    working_directory: /sourceforts-server
    docker:
      - image: docker
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: /sourceforts-server
      - run: |
          docker build -t sourceforts/server:gdb-$CIRCLE_BUILD_NUM -t sourceforts/server:gdb .
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          docker push sourceforts/server:gdb-$CIRCLE_BUILD_NUM
          docker push sourceforts/server:gdb
  test:
    working_directory: /sourceforts-server
    docker:
      - image: docker
    steps:
      - setup_remote_docker
      - checkout
      - attach_workspace:
          at: /sourceforts-server
      - run: mkdir -p sourceforts
      - run: docker build -t sourceforts/server-test .
        
workflows:
  version: 2
  test:
    jobs:
      - test
  server:
    jobs:
      - download:
          context: sourceforts-server
      - unarchive:
          requires:
            - download
      - build:
          context: sourceforts-server
          requires:
            - unarchive
          filters:
            branches:
              only: master
      - build-gdb:
          context: sourceforts-server
          requires:
            - unarchive
          filters:
            branches:
              only: gdb
